import React from "react";
import { useState } from 'react';
import { Link, useNavigate, useLocation } from 'react-router-dom';
import { FileSearch, Sparkles } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

export default function Auth({ mode }) {
  const isRegister = mode === 'register'; const { login, register } = useAuth(); const navigate = useNavigate(); const location = useLocation();
  const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setError('');setBusy(true);try{isRegister?await register(name,email,password):await login(email,password);navigate(location.state?.from || '/');}catch(err){setError(err.response?.data?.detail || 'Unable to continue. Check the API connection and try again.');}finally{setBusy(false);}}
  return <div className="auth-screen"><div className="auth-visual"><div className="auth-brand"><div className="brand-mark"><Sparkles/></div><strong>ResumeIQ</strong></div><div className="auth-pitch"><span className="pill light"><Sparkles size={14}/> YOUR NEXT CAREER MOVE</span><h1>Make your resume<br/><em>work smarter.</em></h1><p>Understand your strengths, uncover skill gaps, and prepare for the opportunities you want.</p><div className="auth-feature"><span><FileSearch size={18}/></span><div><b>Evidence-based matching</b><small>Compare your experience with real job requirements.</small></div></div><div className="auth-feature"><span><Sparkles size={18}/></span><div><b>Actionable insights</b><small>Get clear suggestions to strengthen your profile.</small></div></div></div><div className="auth-foot">Your career journey, made clearer.</div></div><div className="auth-form-side"><form className="auth-card" onSubmit={submit}><div className="mobile-brand"><div className="brand-mark"><Sparkles/></div><strong>ResumeIQ</strong></div><span className="eyebrow">WELCOME {isRegister?'ABOARD':'BACK'}</span><h2>{isRegister?'Create your account':'Sign in to your workspace'}</h2><p className="muted">{isRegister?'Start turning your resume into actionable career insights.':'Continue exploring your resume insights and analysis history.'}</p>{error&&<div className="alert">{error}</div>}{isRegister&&<label>Full name<input required minLength="2" value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label>}<label>Email address<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<input required type="password" minLength={isRegister?8:1} value={password} onChange={e=>setPassword(e.target.value)} placeholder={isRegister?'At least 8 characters':'Your password'}/></label><button className="btn primary full" disabled={busy}>{busy?'Please wait…':isRegister?'Create account':'Sign in'}</button><p className="auth-switch">{isRegister?'Already have an account?':'New to ResumeIQ?'} <Link to={isRegister?'/login':'/register'}>{isRegister?'Sign in':'Create an account'}</Link></p><p className="privacy-note">Your resume is private to your account. AI results are guidance, not hiring decisions.</p></form></div></div>;
}
