import React from "react";
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { FileText, BriefcaseBusiness, ScanSearch, TrendingUp, ArrowUpRight, Sparkles, Plus } from 'lucide-react';
import api from '../services/api';

export default function Dashboard(){
 const [data,setData]=useState(null); const [error,setError]=useState('');
 useEffect(()=>{api.get('/dashboard').then(r=>setData(r.data)).catch(e=>setError(e.response?.data?.detail||'Could not load dashboard.'));},[]);
 const stats=[{label:'Resumes uploaded',value:data?.resume_count??'—',icon:FileText,tint:'blue'},{label:'Job descriptions',value:data?.job_count??'—',icon:BriefcaseBusiness,tint:'violet'},{label:'Analyses completed',value:data?.analysis_count??'—',icon:ScanSearch,tint:'teal'},{label:'Average match score',value:data?`${data.average_match_score}%`:'—',icon:TrendingUp,tint:'amber'}];
 return <div className="stack-xl"><section className="welcome-row"><div><span className="eyebrow">YOUR OVERVIEW</span><h2>Good to see you again.</h2><p className="muted">Turn your experience into a clearer picture of your next opportunity.</p></div><Link className="btn primary" to="/analyze"><Plus size={17}/> New analysis</Link></section>{error&&<div className="alert">{error}</div>}<section className="stats-grid">{stats.map(s=><div className="stat-card" key={s.label}><div className={`stat-icon ${s.tint}`}><s.icon size={19}/></div><span className="stat-label">{s.label}</span><strong>{s.value}</strong><small>{s.label==='Average match score'?'Across your saved analyses':'In your workspace'}</small></div>)}</section><section className="hero-card"><div className="hero-copy"><span className="pill light"><Sparkles size={14}/> AI-POWERED CAREER INSIGHTS</span><h2>Know how your resume<br/>matches the role.</h2><p>Upload a resume, add a job description, and get a structured breakdown of your skills, gaps, and next steps.</p><Link to="/analyze" className="btn white">Analyze a resume <ArrowUpRight size={17}/></Link></div><div className="hero-art"><div className="art-orbit orbit-one"/><div className="art-orbit orbit-two"/><div className="art-doc"><div className="doc-top"><span/><span/><span/></div><div className="doc-avatar"/><div className="doc-line long"/><div className="doc-line medium"/><div className="doc-section"/><div className="doc-line long"/><div className="doc-line short"/><div className="doc-line medium"/><div className="doc-chip">MATCH INSIGHTS</div></div><div className="score-float"><div className="score-ring"><span>86</span></div><div><b>Match score</b><small>Illustrative preview</small></div></div></div></section><section className="panel"><div className="section-heading"><div><h3>Recent analyses</h3><p className="muted">Your latest resume matching activity</p></div><Link to="/history" className="text-link">View history <ArrowUpRight size={15}/></Link></div>{!data?<div className="empty-state">Loading recent activity…</div>:data.recent_analyses.length===0?<div className="empty-state"><div className="empty-icon"><FileText/></div><b>No analyses yet</b><p>Start with a resume and a job description to see your insights here.</p><Link to="/analyze" className="btn secondary">Create your first analysis</Link></div>:<div className="recent-list">{data.recent_analyses.map(item=><Link to={`/history/${item.id}`} className="recent-item" key={item.id}><div className="recent-file"><FileText size={18}/></div><div className="recent-meta"><b>Resume analysis #{item.id}</b><small>{new Date(item.created_at).toLocaleString()}</small></div><span className="score-pill">{item.match_score}% match</span><ArrowUpRight size={16} className="subtle-icon"/></Link>)}</div>}</section><p className="disclaimer"><Sparkles size={14}/> Match scores are estimates based on the supplied resume and job description. Review the evidence before making career decisions.</p></div>;
}
